CREATE TABLE IF NOT EXISTS agent_insurer_relations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_user_id TEXT,
    insurer_name TEXT,
    agent_code TEXT,
    spoc_email TEXT,
    upfront_commission_percentage REAL,
    total_commission_percentage REAL,
    name TEXT,
    category TEXT,
    description TEXT,
    status TEXT,
    features TEXT,
    eligibility TEXT,
    term TEXT,
    exclusions TEXT,
    room_rent TEXT,
    premium_indication TEXT,
    insurer_logo_url TEXT,
    brochure_url TEXT,
    wording_url TEXT,
    claim_form_url TEXT,
    updated_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
